name: Fetch API Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (UTC)

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl https://sarvum.onrender.com/service_status
